EXPRESS_SOFTWARE_MEM_INCREASE_TIMES = 2
LIGHT_SOFTWARE_CAP_INCREASE_PERCENTAGE = 0.5
LIGHT_SOFTWARE_MEM_DECREASE_PERCENTAGE = 0.5
POWER_HARDWARE_CAPACITY_PERCENTAGE = 0.25
POWER_HARDWARE_MEMORY_INCREASE_PERCENTAGE = 0.75
HEAVY_HARDWARE_CAPACITY_INCREASE_TIMES = 2
HEAVY_HARDWARE_MEMORY_PERCENTAGE = 0.75
